FROM node:22-alpine AS base
    ENV PNPM_HOME="/pnpm"
    ENV PATH="$PNPM_HOME:$PATH"
    RUN corepack enable

# ==================
# ==== builder =====
# ==================
FROM base AS builder
    WORKDIR /app

    # copy workspace manifests first for dependency caching
    COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
    COPY apps/web/package.json ./apps/web/

    RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
        pnpm install --frozen-lockfile

    COPY apps/web ./apps/web

    RUN pnpm --filter @soundome/web build

# ==================
# ==== runner ======
# ==================
FROM nginx:stable-alpine AS runner

    COPY --from=builder /app/data/web /usr/share/nginx/html

    EXPOSE 80

    CMD ["nginx", "-g", "daemon off;"]
